CREATE TABLE Supplier
(
	Id INT IDENTITY NOT NULL PRIMARY KEY,
	UserId NVARCHAR(450) NOT NULL,
	Name VARCHAR(100) NOT NULL,

	CONSTRAINT FK_Supplier_AspNetUsers_UserId 
		FOREIGN KEY (UserId) REFERENCES AspNetUsers(Id)

)
